repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        name: ðŸŽ¨ black (formatage)
        args:
          - --line-length=120

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: ðŸ”€ isort (imports)
        args:
          - --profile=black
          - --line-length=120


  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        name: ðŸ§ª flake8 (analyse statique)
        args:
          - --max-line-length=120

# ðŸ”’ pre-commit-hooks â€” sÃ©curitÃ© et hygiÃ¨ne de dÃ©pÃ´t
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
